"""Central configuration file for the project. All pipeline scripts import their paths,
hopsworks settings, feature-store object names, etc. from here including the variables
specified in the .env-file.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load local environment variables from `.env`.
load_dotenv()


# ---------------------------------------------------------------------------
# Project directories
# ---------------------------------------------------------------------------
# ROOT_DIR points to the repository root.
ROOT_DIR = Path(__file__).resolve().parents[1]

# Local data and artifact directories.
DATA_RAW_DIR = ROOT_DIR / "data" / "raw"
DATA_FEATURES_DIR = ROOT_DIR / "data" / "features"
MODEL_DIR = ROOT_DIR / "models"
REPORTS_DIR = ROOT_DIR / "reports"


# ---------------------------------------------------------------------------
# Local artifact paths
# ---------------------------------------------------------------------------
# Reports generated by the pipelines.
BEST_PARAMS_PATH = REPORTS_DIR / "best_params.json"
TUNING_RESULTS_PATH = REPORTS_DIR / "tuning_results.csv"
SELECTED_FEATURES_PATH = REPORTS_DIR / "selected_features.json"
PERMUTATION_IMPORTANCE_PATH = REPORTS_DIR / "permutation_importance.csv"
FEATURE_CORRELATION_MATRIX_PATH = REPORTS_DIR / "feature_correlation_matrix.csv"
HIGH_CORRELATION_PAIRS_PATH = REPORTS_DIR / "highly_correlated_features.csv"
TARGET_CORRELATION_PATH = REPORTS_DIR / "target_correlation.csv"
BACKTESTING_RESULTS_PATH = REPORTS_DIR / "backtesting_results.csv"
LATEST_PREDICTION_PATH = REPORTS_DIR / "latest_prediction.json"
PREDICTION_LOG_PATH = REPORTS_DIR / "prediction_log.csv"
MONITORING_RESULTS_PATH = REPORTS_DIR / "monitoring_results.csv"
MODEL_COMPARISON_RESULTS_PATH = REPORTS_DIR / "model_comparison_results.csv"

# Local cache of engineered training features.
FEATURE_CACHE_PATH = DATA_FEATURES_DIR / "temperature_features.parquet"

# Local model path before uploading the model artifact to hopsworks Model Registry.
MODEL_LOCAL_PATH = MODEL_DIR / "model.joblib"


# ---------------------------------------------------------------------------
# Hopsworks connection settings
# ---------------------------------------------------------------------------
# HOPSWORKS_HOST and HOPSWORKS_PORT default to the managed EU-West endpoint.
# HOPSWORKS_PROJECT and HOPSWORKS_API_KEY must be provided in `.env`.
HOPSWORKS_HOST = os.getenv("HOPSWORKS_HOST", "eu-west.cloud.hopsworks.ai")
HOPSWORKS_PORT = int(os.getenv("HOPSWORKS_PORT", "443"))
HOPSWORKS_PROJECT = os.getenv("HOPSWORKS_PROJECT")
HOPSWORKS_API_KEY = os.getenv("HOPSWORKS_API_KEY")

# We use the Python engine, which is the expected setup for local execution.
HOPSWORKS_ENGINE = os.getenv("HOPSWORKS_ENGINE", "python")


# ---------------------------------------------------------------------------
# Location and weather API settings
# ---------------------------------------------------------------------------
# Default location: Basel, Switzerland.
# Values can be overridden via `.env`.
LATITUDE = float(os.getenv("LATITUDE", "47.5596"))
LONGITUDE = float(os.getenv("LONGITUDE", "7.5886"))
LOCATION_ID = os.getenv("LOCATION_ID", "basel")
TIMEZONE = os.getenv("TIMEZONE", "Europe/Zurich")


# ---------------------------------------------------------------------------
# Forecasting target configuration
# ---------------------------------------------------------------------------
# The model predicts the temperature `FORECAST_HORIZON_HOURS` hours after the
# current feature event time.
#
# Example with FORECAST_HORIZON_HOURS = 6:
#   feature event_time:    2026-04-29 00:00:00
#   prediction target:     2026-04-29 06:00:00
#   target column name:    temperature_2m_next_6h
FORECAST_HORIZON_HOURS = int(os.getenv("FORECAST_HORIZON_HOURS", "6"))

TARGET_COLUMN = f"temperature_2m_next_{FORECAST_HORIZON_HOURS}h"


# ---------------------------------------------------------------------------
# Hopsworks Feature Store object names
# ---------------------------------------------------------------------------
# Training data and live inference data are stored in separate feature groups.
# This prevents mixing rows with known historical labels and rows where the future
# target is not known yet.
TRAINING_FEATURE_GROUP_NAME = "temperature_forecast_training_features"
TRAINING_FEATURE_GROUP_VERSION = 3

INFERENCE_FEATURE_GROUP_NAME = "temperature_forecast_inference_features"
INFERENCE_FEATURE_GROUP_VERSION = 3

# Feature Views define the reusable query/interface used by training and
# inference pipelines. Separate views keep training and inference concerns clear.
TRAINING_FEATURE_VIEW_NAME = "temperature_forecast_training_fv"
TRAINING_FEATURE_VIEW_VERSION = 3

INFERENCE_FEATURE_VIEW_NAME = "temperature_forecast_inference_fv"
INFERENCE_FEATURE_VIEW_VERSION = 3


# ---------------------------------------------------------------------------
# Hopsworks Model Registry settings
# ---------------------------------------------------------------------------
# Baseline and final models use separate registry names to avoid accidentally
# loading a newly uploaded baseline model as the latest production candidate.
BASELINE_MODEL_NAME = "temperature_forecast_baseline_regressor"
FINAL_MODEL_NAME = "temperature_forecast_final_regressor"

# Default model name used by inference.
MODEL_NAME = FINAL_MODEL_NAME

# Optional pinned model version.
#
# If MODEL_VERSION is empty or not set, the inference pipeline loads the latest
# available model version from the hopsworks Model Registry.
#
# Example:
#   MODEL_VERSION=2   -> load version 2 explicitly
#   MODEL_VERSION=    -> load latest available version
MODEL_VERSION_RAW = os.getenv("MODEL_VERSION")

try:
    MODEL_VERSION = int(MODEL_VERSION_RAW) if MODEL_VERSION_RAW else None
except ValueError as exc:
    raise ValueError("MODEL_VERSION must be an integer or empty.") from exc


# ---------------------------------------------------------------------------
# Lightweight configuration validation
# ---------------------------------------------------------------------------
# These checks fail fast for common configuration mistakes while still keeping
# imports simple. Secrets are not validated here and are never printed.
if FORECAST_HORIZON_HOURS <= 0:
    raise ValueError("FORECAST_HORIZON_HOURS must be greater than 0.")

if not LOCATION_ID:
    raise ValueError("LOCATION_ID must not be empty.")

if not TIMEZONE:
    raise ValueError("TIMEZONE must not be empty.")

if not -90 <= LATITUDE <= 90:
    raise ValueError("LATITUDE must be between -90 and 90.")

if not -180 <= LONGITUDE <= 180:
    raise ValueError("LONGITUDE must be between -180 and 180.")
